spring:
  cloud:
    gateway:
      routes:
        - id: bookinfo
          uri: http://localhost:8081
          predicates:
            - Path=/books/**
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,gateway